function createfigure(cdata1, XData1, YData1, XData2, YData2, cdata2, YData3, YData4, cdata3, cdata4, cdata5, cdata6, cdata7, cdata8, cdata9)
%CREATEFIGURE(cdata1, XData1, YData1, XData2, YData2, cdata2, YData3, YData4, cdata3, cdata4, cdata5, cdata6, cdata7, cdata8, cdata9)
%  CDATA1:  image cdata
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  CDATA2:  image cdata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  CDATA3:  image cdata
%  CDATA4:  image cdata
%  CDATA5:  image cdata
%  CDATA6:  image cdata
%  CDATA7:  image cdata
%  CDATA8:  image cdata
%  CDATA9:  image cdata

%  Auto-generated by MATLAB on 17-Feb-2021 11:16:31

% Create figure
figure1 = figure('InvertHardcopy','off','PaperUnits','normalized',...
    'Tag','Graphics',...
    'NumberTitle','off',...
    'Name','SPM12 (7771): Graphics',...
    'Color',[1 1 1]);
colormap(gray(64));

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.00901768172888019 0.563707900323174 0.214774281805746 0.177396869653381]);
hold(axes1,'on');

% Create image
image(cdata1,'HitTest','off','Tag','Transverse','Parent',axes1);

% Create line
line(XData1,YData1,'HitTest','off','Parent',axes1,'Color',[0 0 1]);

% Create line
line(XData2,YData2,'HitTest','off','Parent',axes1,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 157.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 187.5]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.00901768172888019 0.747574538163913 0.214774281805746 0.146091539714549]);
hold(axes2,'on');

% Create image
image(cdata2,'HitTest','off','Tag','Transverse','Parent',axes2);

% Create line
line(XData1,YData3,'HitTest','off','Parent',axes2,'Color',[0 0 1]);

% Create line
line(XData2,YData4,'HitTest','off','Parent',axes2,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.5 157.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.5 154.5]);
box(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.233203728240508 0.747574538163913 0.255813953488372 0.146091539714549]);
hold(axes3,'on');

% Create image
image(cdata3,'HitTest','off','Tag','Transverse','Parent',axes3);

% Create line
line(YData2,YData3,'HitTest','off','Parent',axes3,'Color',[0 0 1]);

% Create line
line(YData1,YData4,'HitTest','off','Parent',axes3,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0.5 187.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0.5 154.5]);
box(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.50901768172888 0.547824350610228 0.214774281805746 0.192759885011964]);
hold(axes4,'on');

% Create image
image(cdata4,'HitTest','off','Tag','Transverse','Parent',axes4);

% Create line
line(XData1,YData1,'HitTest','off','Parent',axes4,'Color',[0 0 1]);

% Create line
line(XData2,YData2,'HitTest','off','Parent',axes4,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0.5 157.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0.5 187.5]);
box(axes4,'on');
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.50901768172888 0.747614302016746 0.214774281805746 0.158743434715735]);
hold(axes5,'on');

% Create image
image(cdata5,'HitTest','off','Tag','Transverse','Parent',axes5);

% Create line
line(XData1,YData3,'HitTest','off','Parent',axes5,'Color',[0 0 1]);

% Create line
line(XData2,YData4,'HitTest','off','Parent',axes5,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0.5 157.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0.5 154.5]);
box(axes5,'on');
hold(axes5,'off');
% Set the remaining axes properties
set(axes5,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes6 = axes('Parent',figure1,...
    'Position',[0.733203728240508 0.747614302016746 0.255813953488372 0.158743434715735]);
hold(axes6,'on');

% Create image
image(cdata6,'HitTest','off','Tag','Transverse','Parent',axes6);

% Create line
line(YData2,YData3,'HitTest','off','Parent',axes6,'Color',[0 0 1]);

% Create line
line(YData1,YData4,'HitTest','off','Parent',axes6,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0.5 187.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0.5 154.5]);
box(axes6,'on');
hold(axes6,'off');
% Set the remaining axes properties
set(axes6,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes7 = axes('Parent',figure1,...
    'Position',[0.00901768172888019 0.0626035265293007 0.214774281805746 0.192759885011964]);
hold(axes7,'on');

% Create image
image(cdata7,'HitTest','off','Tag','Transverse','Parent',axes7);

% Create line
line(XData1,YData1,'HitTest','off','Parent',axes7,'Color',[0 0 1]);

% Create line
line(XData2,YData2,'HitTest','off','Parent',axes7,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[0.5 157.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[0.5 187.5]);
box(axes7,'on');
hold(axes7,'off');
% Set the remaining axes properties
set(axes7,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes8 = axes('Parent',figure1,...
    'Position',[0.00901768172888019 0.262393477935818 0.214774281805746 0.158743434715735]);
hold(axes8,'on');

% Create image
image(cdata8,'HitTest','off','Tag','Transverse','Parent',axes8);

% Create line
line(XData1,YData3,'HitTest','off','Parent',axes8,'Color',[0 0 1]);

% Create line
line(XData2,YData4,'HitTest','off','Parent',axes8,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes8,[0.5 157.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes8,[0.5 154.5]);
box(axes8,'on');
hold(axes8,'off');
% Set the remaining axes properties
set(axes8,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
% Create axes
axes9 = axes('Parent',figure1,...
    'Position',[0.233203728240508 0.262393477935818 0.255813953488372 0.158743434715735]);
hold(axes9,'on');

% Create image
image(cdata9,'HitTest','off','Tag','Transverse','Parent',axes9);

% Create line
line(YData2,YData3,'HitTest','off','Parent',axes9,'Color',[0 0 1]);

% Create line
line(YData1,YData4,'HitTest','off','Parent',axes9,'Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes9,[0.5 187.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes9,[0.5 154.5]);
box(axes9,'on');
hold(axes9,'off');
% Set the remaining axes properties
set(axes9,'ContextMenu','Layer','top','XTick',[],'YTick',[]);
